Annie use default tagging
hashicorp/terraform-aws-terraform-enterprise pull request #183
Opened 2021-06-11 18:56 UTC by anniehedgpeth

## Background

A [task](https://app.asana.com/0/1181500399442529/1200343533684843/f) was done previously that standardizes on tagging across tests (and other repo modules), but the `OkToDelete` tag was neglected. Also, the change only affected the `common_tags` variable; it did not ensure that every taggable resource was being tagged. This is being done in this branch for the test suites by adding the `default_tags` to the AWS provider for the test modules. Consequently, it required that I add a separate tag variable for the autoscaling group tags, as explained in the variable description.

[Asana Task](https://app.asana.com/0/1181500399442529/1200460471392854/f)

## How Has This Been Tested

`terraform plan` was run locally for each test. I will `/test all` here in the PR.

## This PR makes me feel

![default](https://media.giphy.com/media/l41lQ6WPSINy8LBXq/giphy.gif)

2021-06-11 18:57 UTC, anniehedgpeth commented
That was a bad choice of gifs, and I am sorry if it gives you a headache. 😳

2021-06-11 19:27 UTC, anniehedgpeth commented
/test all

2021-06-11 22:40 UTC, anniehedgpeth commented
/test all

2021-06-11 23:20 UTC, anniehedgpeth commented
/test all

2021-06-14 18:22 UTC, anniehedgpeth commented
/test private-active-active

2021-06-14 18:25 UTC, anniehedgpeth commented
/test private-tcp-active-active

2021-06-14 19:04 UTC, anniehedgpeth commented
/test private-active-active

2021-06-15 16:04 UTC, anniehedgpeth commented
/test all

2021-06-15 17:23 UTC, anniehedgpeth commented
/test private-active-active destroy=false

2021-06-15 20:37 UTC, aaron-lane requested changes
I identified the source of the latest test failure 👁️‍🗨️

2021-06-15 20:37 UTC, aaron-lane commented on tests/private-active-active/main.tf
>  data "aws_instances" "main" {
The filter logic for this data source is now insufficient as the internal proxy instance has the tags but not the key needed to authorize our SOCKS5 proxy connection. This isn't an issue for private-tcp-active-active as it was already designed to use the internal proxy instance for the SOCKS5 proxy as well: https://github.com/hashicorp/terraform-aws-terraform-enterprise/blob/annie-use-default-tagging/tests/private-tcp-active-active/outputs.tf#L34. We should update this case to do the same (and probably update the output names on both tests to be `proxy_instance_id`.

2021-06-16 15:26 UTC, anniehedgpeth commented
/destroy private-active-active

2021-06-16 15:58 UTC, anniehedgpeth commented
/destroy private-active-active

2021-06-16 16:33 UTC, anniehedgpeth commented
/test all

2021-06-16 17:37 UTC, anniehedgpeth commented
/test private-active-active

2021-06-16 18:19 UTC, aaron-lane approved these changes
LGTM 🐛 

We'll take care of the latest private-active-active issue separately.

2021-06-16 18:20 UTC, merged