Utility proxy
hashicorp/terraform-aws-terraform-enterprise pull request #229
Opened 2022-03-28 18:44 UTC by sandrampeter

## Background

[proxy utility for AWS](https://app.asana.com/0/1200681690870921/1201744486584882/f)

2022-03-29 02:16 UTC, sandrampeter commented
/test all

2022-03-29 02:55 UTC, sandrampeter commented
/test all

2022-03-29 15:43 UTC, sandrampeter commented
/test all

2022-03-29 20:11 UTC, sandrampeter commented
/test all destroy=false

2022-03-30 12:37 UTC, sandrampeter commented
/test all destroy=false

2022-03-30 18:34 UTC, sandrampeter commented
/test all

2022-03-31 21:28 UTC, sandrampeter commented
/test all

2022-04-01 02:47 UTC, sandrampeter commented
/test all

2022-04-01 17:15 UTC, anniehedgpeth requested changes
Looks good other than using empty strings as default variable values. They can sometimes obfuscate issues, so we'd rather use `null`. (For context, we created this standard [back here](https://app.asana.com/0/1181500399442529/1200487922889435/f).)

2022-04-01 17:15 UTC, anniehedgpeth commented on fixtures/test_proxy/main.tf
> +  mitmproxy_ca_private_key_secret = var.mitmproxy_ca_private_key_secret != null ? var.mitmproxy_ca_private_key_secret : ""
Instead of `""` can we use `null`?

2022-04-01 17:15 UTC, anniehedgpeth commented on fixtures/test_proxy/variables.tf
> +  default     = ""
We want to use `null` as opposed to empty strings for defaults.
```suggestion
  default     = null
```

2022-04-01 17:15 UTC, anniehedgpeth commented on fixtures/test_proxy/variables.tf
> +  default     = ""
```suggestion
  default     = null
```
Same here.

2022-04-01 17:15 UTC, anniehedgpeth commented on fixtures/test_proxy/variables.tf
> +  default     = ""
```suggestion
  default     = null
```

2022-04-01 18:38 UTC, anniehedgpeth commented
Thanks, @sandrampeter ! Would you mind testing the proxies once more just to make sure there's no unexpected behavior from that change?

2022-04-01 18:54 UTC, sandrampeter commented
/test all

2022-04-01 19:34 UTC, sandrampeter commented
> Thanks, @sandrampeter ! Would you mind testing the proxies once more just to make sure there's no unexpected behavior from that change?

@anniehedgpeth its done

2022-04-01 19:35 UTC, anniehedgpeth approved these changes

2022-04-01 19:45 UTC, merged